# Generated by Django 2.2.13 on 2021-01-18 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenseapp', '0008_auto_20200324_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nimi')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Vastaanotettu'), ('E', 'Muokattu'), ('C', 'Asiahyväksytty'), ('A', 'Hallinnollisesti hyväksytty'), ('P', 'Maksettu')], max_length=5, verbose_name='Tyyppi')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Valtuutettu')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Workflow', verbose_name='Työkulku')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Vastaanotettu'), ('E', 'Muokattu'), ('C', 'Asiahyväksytty'), ('A', 'Hallinnollisesti hyväksytty'), ('P', 'Maksettu')], max_length=5, verbose_name='Tyyppi')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lisätietoja')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Expense', verbose_name='Kulukorvaus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Merkinnän tekijä')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Workflow', verbose_name='Työkulku'),
            preserve_default=False,
        ),
    ]
