# Generated by Django 2.2.13 on 2021-01-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_auto_20210118_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='num',
            field=models.CharField(default=1, max_length=4, verbose_name='Tositenumero'),
            preserve_default=False,
        ),
    ]
