# Generated by Django 2.2.13 on 2021-01-18 13:20

from django.db import migrations, models
import expenseapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0010_expense_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='personno',
            field=models.CharField(blank=True, help_text='If you apply for an expense reimbursement for a local group, enter the group’s business ID here. Kilometric allowances and daily subsistence allowances can not be applied for with a business ID.', max_length=11, null=True, validators=[expenseapp.models.validate_hetu_or_businessid], verbose_name='Person number'),
        ),
    ]
