# Generated by Django 2.2.13 on 2021-09-19 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenseapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0012_workflow_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdimension',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='personno',
            field=models.CharField(blank=True, help_text='Required if applying for kilometric or daily subsistence allowances due to tax reporting. If you apply for an expense reimbursement for a local group, enter the group’s business ID here. Kilometric allowances and daily subsistence allowances can not be applied for with a business ID.', max_length=11, null=True, validators=[expenseapp.models.validate_hetu_or_businessid], verbose_name='Person number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Workflow', verbose_name='Työkulku'),
        ),
        migrations.AlterField(
            model_name='expenseevent',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Expense', verbose_name='Kulukorvaus'),
        ),
        migrations.AlterField(
            model_name='expenseevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Merkinnän tekijä'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='accountdimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenseapp.AccountDimension', verbose_name='Cost centre'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Expense'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expensetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.ExpenseType', verbose_name='Expense type'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Valtuutettu'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Workflow', verbose_name='Työkulku'),
        ),
    ]
