# Generated by Django 3.2.13 on 2024-04-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_merge_0008_auto_20200324_1133_0008_auto_20200324_1141'),
        ('expenseapp', '0013_auto_20220224_1126'),
    ]

    operations = [
    ]
