# Generated by Django 5.2.12 on 2026-03-28 15:02

from django.db import migrations


def copy_expense_owners_to_lines(apps, schema_editor):
    ExpenseLine = apps.get_model('expenseapp', 'ExpenseLine')
    lines_to_update = []
    for line in ExpenseLine.objects.select_related('expense').iterator():
        if getattr(line, 'expense_id', None):
            line.user_id = line.expense.user_id
            line.organisation_id = line.expense.organisation_id
            lines_to_update.append(line)
            
    if lines_to_update:
        ExpenseLine.objects.bulk_update(lines_to_update, ['user_id', 'organisation_id'], batch_size=1000)

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0015_expenseline_organisation_expenseline_user_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_expense_owners_to_lines, reverse_copy),
    ]
